version: 2.1
orbs:
  katalon-studio: katalon/katalon-studio@23.0.11
workflows:
    example-workflow:
      jobs:
        - katalon-studio/run:
            command_arguments: -retry=0 -testSuitePath="Test Suites/check title" -executionProfile="default" -browserType="Chrome" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true 